---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-netstat-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-netstat-exporter
  namespace: pod-netstat-exporter
  labels:
    app: pod-netstat-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: pod-netstat-exporter
  name: pod-netstat-exporter
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    name: pod-netstat-exporter
  name: pod-netstat-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-netstat-exporter
subjects:
  - kind: ServiceAccount
    name: pod-netstat-exporter
    namespace: pod-netstat-exporter
